class ReadError(Exception):
    pass


class InitError(Exception):
    pass